# Generated by Django 4.2.3 on 2023-07-12 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chercheur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('grade', models.CharField(choices=[('PES', 'PES'), ('PH', 'PH'), ('PA', 'PA'), ('Doc', 'Doc'), ('Autre', 'Autre')], max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('photo', models.ImageField(blank=True, default='chercheur_photos/chercheur.png', null=True, upload_to='chercheur_photos/')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='chercheur_files/')),
                ('information', models.TextField(blank=True, null=True)),
                ('annee_inscription', models.IntegerField(blank=True, null=True)),
                ('date_soutenance', models.DateField(blank=True, null=True)),
                ('co_encadrant', models.ForeignKey(blank=True, limit_choices_to={'grade__in': ['PES', 'PH', 'PA']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_encadre', to='structure.chercheur')),
                ('encadrant', models.ForeignKey(blank=True, limit_choices_to={'grade__in': ['PES', 'PH']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encadre', to='structure.chercheur')),
            ],
        ),
        migrations.CreateModel(
            name='Laboratoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=50)),
                ('intitule', models.CharField(max_length=200)),
                ('departement', models.CharField(blank=True, choices=[('Informatique', 'Informatique'), ('Mathématique', 'Mathématique'), ('Physique', 'Physique'), ('SVT', 'SVT')], max_length=50, null=True)),
                ('date_creation', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('photo', models.ImageField(blank=True, default='labo_photos/fs.jpg', null=True, upload_to='laboratoire_photos/')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='laboratoire_files/')),
                ('information', models.TextField(blank=True, null=True)),
                ('directeur', models.ForeignKey(blank=True, limit_choices_to={'grade__in': ['PES']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directeur_labo', to='structure.chercheur')),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aka', models.CharField(max_length=50)),
                ('intitule', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, default='equipe_photos/equipe.jpg', null=True, upload_to='equipe_photos/')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='equipe_files/')),
                ('information', models.TextField(blank=True, null=True)),
                ('labo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laboratoire_equipe', to='structure.laboratoire')),
                ('respo', models.ForeignKey(blank=True, limit_choices_to={'grade__in': ['PES', 'PH']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respo', to='structure.chercheur')),
            ],
        ),
        migrations.AddField(
            model_name='chercheur',
            name='equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipe_chercheur', to='structure.equipe'),
        ),
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=50)),
                ('intitule', models.CharField(max_length=300)),
                ('genre', models.CharField(choices=[('Production scientifique', 'Production scientifique'), ('Encadrement scientifique', 'Encadrement scientifique'), ('Événement scientifique', 'Événement scientifique')], max_length=50)),
                ('type_pub', models.CharField(blank=True, choices=[], max_length=50, null=True)),
                ('date_pub', models.DateField(blank=True, null=True)),
                ('notation', models.FloatField(blank=True, default=0, null=True)),
                ('photo', models.ImageField(blank=True, default='activite_photos/activite.jpg', null=True, upload_to='activite_photos/')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='activite_files/')),
                ('information', models.TextField(blank=True, null=True)),
                ('equipes', models.ManyToManyField(blank=True, related_name='equipe_activite', to='structure.equipe')),
            ],
        ),
    ]
