# Generated by Django 4.2.3 on 2023-07-16 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0004_rename_datep_publication_date_publication_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='alias',
        ),
        migrations.AddField(
            model_name='publication',
            name='ISBN',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='activite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activite_publication', to='structure.activite'),
        ),
    ]
