# Generated by Django 4.2.3 on 2023-07-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0006_alter_chercheur_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chercheur',
            name='grade',
            field=models.CharField(blank=True, choices=[('PES', 'PES'), ('PH', 'PH'), ('PA', 'PA'), ('Docteur', 'Docteur')], max_length=10, null=True),
        ),
    ]
