# Generated by Django 4.2.3 on 2023-07-16 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0008_alter_chercheur_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chercheur',
            name='grade',
            field=models.CharField(blank=True, choices=[('PES', 'PES'), ('PH', 'PH'), ('PA', 'PA'), ('Docteur', 'Docteur')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='doctorant',
            name='chercheur',
            field=models.OneToOneField(limit_choices_to={'grade__isnull': True}, on_delete=django.db.models.deletion.CASCADE, related_name='chercheur_doctorant', to='structure.chercheur'),
        ),
    ]
