# Generated by Django 4.2.3 on 2023-07-17 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0009_alter_chercheur_grade_alter_doctorant_chercheur'),
    ]

    operations = [
        migrations.AddField(
            model_name='chercheur',
            name='annee_inscription',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chercheur',
            name='co_encadrant',
            field=models.ForeignKey(blank=True, limit_choices_to={'grade__in': ['PES', 'PH', 'PA']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_encadrant_doctorant', to='structure.chercheur'),
        ),
        migrations.AddField(
            model_name='chercheur',
            name='date_soutenance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chercheur',
            name='encadrant',
            field=models.ForeignKey(blank=True, limit_choices_to={'grade__in': ['PES', 'PH']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encadrant_doctorant', to='structure.chercheur'),
        ),
        migrations.AddField(
            model_name='chercheur',
            name='these',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
