# Generated by Django 4.2.3 on 2023-07-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0011_remove_auteurpublication_chercheur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_publication', models.CharField(choices=[('Article', 'Article scientifique'), ('Actes', 'Actes de congrès'), ('Communication', 'Communication orale'), ('Ouvrage', 'Ouvrage de recherche')], max_length=30)),
                ('libelle', models.CharField(max_length=100)),
                ('date_publication', models.DateField()),
                ('information', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, default='production_photos/production.jpg', null=True, upload_to='production_photos/')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='production_files/')),
                ('auteurs', models.ManyToManyField(related_name='auteur_production', to='structure.chercheur')),
            ],
        ),
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_activite', models.CharField(choices=[('Projets financés', 'Projets financés'), ('Manifestations scientifiques', 'Manifestations scientifiques'), ('Conventions de partenariat', 'Conventions de partenariat'), ('Expertises et prestations de service', 'Expertises et prestations de service'), ('Recherche et développement', 'Recherche et développement')], max_length=70)),
                ('libelle', models.CharField(max_length=100)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('photo', models.ImageField(blank=True, default='activite_photos/production.jpg', null=True, upload_to='activite_photos/')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='activite_files/')),
                ('equipes', models.ManyToManyField(related_name='equipe_activite', to='structure.equipe')),
            ],
        ),
    ]
