# Generated by Django 4.2.3 on 2023-07-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0012_production_activite'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='equipes',
            field=models.ManyToManyField(related_name='equipe_production', to='structure.equipe'),
        ),
    ]
