# Generated by Django 4.2.3 on 2023-07-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0013_production_equipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activite',
            name='photo',
            field=models.ImageField(blank=True, default='activite_photos/activite.jpg', null=True, upload_to='activite_photos/'),
        ),
        migrations.AlterField(
            model_name='production',
            name='fichier',
            field=models.FileField(blank=True, default='production_files/test_pdf.pdf', null=True, upload_to='production_files/'),
        ),
    ]
