# Generated by Django 4.2.3 on 2023-07-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0015_alter_activite_fichier_alter_chercheur_fichier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='information',
            field=models.TextField(blank=True, null=True),
        ),
    ]
