# Generated by Django 4.2.3 on 2023-07-22 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0016_activite_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='equipes',
        ),
    ]
